from utils.get_root_path import get_root_path
from typing import Final

ROOT: Final = get_root_path()

DATASET_PATH: Final = f"{ROOT}/datasets"
DATASET_TRAIN_PATH: Final = f"{DATASET_PATH}/train"
DATASET_TEST_PATH: Final = f"{DATASET_PATH}/test"

DATASET_TRAIN_BUTTERFLY_PATH: Final = f"{DATASET_TRAIN_PATH}/butterfly"
DATASET_TRAIN_CAT_PATH: Final = f"{DATASET_TRAIN_PATH}/cat"
DATASET_TRAIN_CHICKEN_PATH: Final = f"{DATASET_TRAIN_PATH}/chicken"
DATASET_TRAIN_COW_PATH: Final = f"{DATASET_TRAIN_PATH}/cow"
DATASET_TRAIN_DOG_PATH: Final = f"{DATASET_TRAIN_PATH}/dog"
DATASET_TRAIN_ELEPHANT_PATH: Final = f"{DATASET_TRAIN_PATH}/elephant"
DATASET_TRAIN_HORSE_PATH: Final = f"{DATASET_TRAIN_PATH}/horse"
DATASET_TRAIN_SHEEP_PATH: Final = f"{DATASET_TRAIN_PATH}/sheep"
DATASET_TRAIN_SPIDER_PATH: Final = f"{DATASET_TRAIN_PATH}/spider"
DATASET_TRAIN_SQUIRREL_PATH: Final = f"{DATASET_TRAIN_PATH}/squirrel"

DATASET_TEST_BUTTERFLY_PATH: Final = f"{DATASET_TEST_PATH}/butterfly"
DATASET_TEST_CAT_PATH: Final = f"{DATASET_TEST_PATH}/cat"
DATASET_TEST_CHICKEN_PATH: Final = f"{DATASET_TEST_PATH}/chicken"
DATASET_TEST_COW_PATH: Final = f"{DATASET_TEST_PATH}/cow"
DATASET_TEST_DOG_PATH: Final = f"{DATASET_TEST_PATH}/dog"
DATASET_TEST_ELEPHANT_PATH: Final = f"{DATASET_TEST_PATH}/elephant"
DATASET_TEST_HORSE_PATH: Final = f"{DATASET_TEST_PATH}/horse"
DATASET_TEST_SHEEP_PATH: Final = f"{DATASET_TEST_PATH}/sheep"
DATASET_TEST_SPIDER_PATH: Final = f"{DATASET_TEST_PATH}/spider"
DATASET_TEST_SQUIRREL_PATH: Final = f"{DATASET_TEST_PATH}/squirrel"

DATASET_BACKUP_BUTTERFLY: Final = f"{DATASET_PATH}/backup/butterfly"
DATASET_BACKUP_CAT: Final = f"{DATASET_PATH}backup//cat"
DATASET_BACKUP_CHICKEN: Final = f"{DATASET_PATH}backup//chicken"
DATASET_BACKUP_COW: Final = f"{DATASET_PATH}backup//cow"
DATASET_BACKUP_DOG: Final = f"{DATASET_PATH}backup//dog"
DATASET_BACKUP_ELEPHANT: Final = f"{DATASET_PATH}backup//elephant"
DATASET_TEST_HORSE: Final = f"{DATASET_PATH}backup//horse"
DATASET_BACKUP_SHEEP: Final = f"{DATASET_PATH}backup//sheep"
DATASET_BACKUP_SPIDER: Final = f"{DATASET_PATH}backup//spider"
DATASET_BACKUP_SQUIRREL: Final = f"{DATASET_PATH}backup//squirrel"

TRAIN_RATIO: Final = 0.8
TEST_RATIO: Final = 0.2

ROTATIONS_PER_IMAGE: Final = 4
ROTATION_ANGLE_RANGE: Final = (-30, 30)
BRIGHTNESS_ADJUSTMENTS_PER_IMAGE: Final = 4
BRIGHTNESS_RANGE: Final = (0.5, 1.5)
GAUSSIAN_BLUR_PER_IMAGE: Final = 4
GAUSSIAN_RANDOM_BLUR_KERNEL: Final = [(3, 3), (5, 5), (7, 7)]
NOISE_PER_IMAGE: Final = 4
NOISE_NOISE_INTENSITY: Final = (10, 50)
COLOR_JITTER_VARIANTS: Final = 4